---
- name: Create a new user
  user:
      name: "{{ user_name }}"
      password: "{{ user_password }}"
      group: wheel
      state: present
      shell: /bin/bash       
      createhome: yes

- name: add to root group
  shell: usermod -G root "{{user_name}}"  
